### PR TITLE
[feature] expose is_admin in the user api

### PR DESCRIPTION
**Pull request by mnandri**
So that whoever consumes the API can use this attribute to
determine if admin functionalities should be made available to
the current user.

### CODE REVIEW

**Comment by elijh** [comment]
interesting. in general, this is information i would like to keep private, but i suppose whomever has api access is already has privileged access. currently, afaik, that is *only* the holder of the monitor token.

can you say a bit more about who is consuming this api and for what purpose?

**Comment by mnandri** [comment]
Yes,  https://<api>/<version>/users/<userid>.json throws a 403 unless you are admin already. Even if you  are querying about yourself, non admin is not authorized for this. So this is not new information that the user is not privileged to see already and an admin can see this from web-app UI already.

The advantage of exposing this on the API is that whoever wants to preserve the leap "privilege" hierarchy can just make this request. It is then synchronized, if it is changed from the provider, it will also reflect on the other side. Plus, you avoid creating your own User data model and unnecessary database requirements that comes with that.

We want to use this on pixelated, to restrict access for viewing "how many users are logged in"... to leap admins only.

**Comment by azul** [comment]
@elijh currently the monitor user and admin users have access to this. So one thing that this api would allow would be for admins to query if other users are admins too. I can't really imagine a situation where you would want to hide that information from admins.
Still it seems to me that this may not be the ideal way to expose this. Maybe if all we need is a query 'Am i an admin?' we should not expose 'Is xy an admin?'
@mnandri I was joking when i said it might take long to merge this. Sorry that I'm bringing this up now. Hadn't thought about it when we worked on this together. What do you think?

**Comment by mnandri** [comment]
yeah, I agree.
We can restrict it to: don't show is_admin unless I'm me. 
How does that sound?

**Comment by mnandri** [comment]
or is_admin defaults to false, unless I'm me and I'm admin.

**Comment by elijh** [comment]
I apologize if it seems like I am holding up a trivial change. That is not my intention. My only approach is this: if there is a change that exposes more information than was previously exposed, there should be a good reason for it. 

It sounds like you have a good reason for it.

I would like to note, however, that in the future I think we should totally separate admin accounts from regular user accounts. In other words, I think it is dangerous to allow admins to get and receive email with the same account that they use to administer the system. There is no good reason to allow this, and a lot of reasons to disallow this.

**Comment by azul** [comment]
Thanks @mnandri , merged it :sparkles: 
:blue_heart:

**Pull request merged**
