### PR TITLE
initial invite model with basic unit test

### PR DESCRIPTION
**Pull request by azul**
Please make sure to run:
  rake couchrest:migrate

That will add the new database to couch.

### CODE REVIEW

**Comment by elijh** [comment]
where does couchrest:migrate needs to be run? we don't have a method to run migrations on deployment...

**Comment by elijh** [comment]
looks great. i can take it from here.

**Comment by kaeff** [comment]
Hi @elijh @azul , the summer of code team in Hamburg is also currently working on invites. You can find our progress here: https://github.com/Alster-Hamburgers/leap_web/tree/feature/invite_code, https://github.com/Alster-Hamburgers/leap_web/issues/4

Can we sync soon to avoid double work? cc @varac

**Comment by elijh** [comment]
I think there is no need to merge. This PR was never functional, and was not really intended to be merged.

**Pull request closed without merging**
